---
- name: Create directory for unbound logs
  ansible.builtin.file: 
    path: "{{ item }}"
    state: directory
    mode: '0750'
    owner: root
    group: root
  with_items:
    - /var/log/unbound

- name: Enable packages gather facts
  ansible.builtin.package_facts:
    manager: auto

- name: Add apparmor local rules (skip if apparmor isn't installed)
  when: "'apparmor' in ansible_facts.packages"
  ansible.builtin.template:
    src: usr.sbin.unbound.j2
    dest: /etc/apparmor.d/local/usr.sbin.unbound
    mode: '0644'
    owner: root
    group: root
  notify:
    - Reload apparmor service

- name: Activate logrotate for unbound
  ansible.builtin.blockinfile:
    create: true
    block: |
      /var/log/unbound/*.log {
              daily
              missingok
              rotate 7
              compress
              compresscmd /usr/bin/pigz
              delaycompress
              notifempty
              create 644 unbound adm
              sharedscripts
              postrotate
                  /usr/sbin/unbound-control log_reopen
              endscript
      }
    path: /etc/logrotate.d/unbound
    mode: '0640'
    owner: root
    group: root

- name: Update root.hints for unbound
  ansible.builtin.get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /etc/unbound/root.hints
    mode: '0644'

- name: Change system nameserver
  when: unbound_resolvconf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: "^nameserver"
    line: "nameserver 127.0.0.1\n"

- name: Copy unbound config file(s)
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/unbound/unbound.conf.d/{{ item }}"
    mode: '0644'
    owner: root
    group: root
  with_items:
    - general.conf
    - forward_zone.conf
    - control.conf
  notify:
    - Restart unbound service

- name: Configure unbound zones
  ansible.builtin.template:
    src: zone.conf.j2
    dest: "/etc/unbound/unbound.conf.d/{{ item.name }}.conf"
    mode: '0644'
    owner: root
    group: root 
  with_items: "{{ unbound_zones }}"
  notify:
    - Restart unbound service
