---
- name: Converge
  hosts: all
  tasks:
    - name: Install requirements
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - gnupg
    - name: "Include leadlineit.unbound"
      ansible.builtin.include_role:
        name: "leadlineit.unbound"
